### ISSUE TITLE
confuse about the alignment

### ISSUE THREAD

**Issue by xujihui1985** [ncw/directio#10]
from the knowledge of page size alignment, I presume that AlignedBlock should return the multiple size of AlignSize, eg: given AlignedSize 4096,  when blocksize 3000 is given, it should align to 4096, but AlignedBlock return 3000 instead, do I misunderstood something?

**Comment by ncw** [comment]
I would guess you are running on macOS - this doesn't need any alignment.

What OS are you using?

**Comment by xujihui1985** [comment]
@ncw I was test on linux kernel version 5.8.15
the test code is as simple as 
```go
package main

import (
  "fmt"
  "github.com/ncw/directio"
)


func main() {
  block := directio.AlignedBlock(3000)
  fmt.Printf("block is %d\n", len(block))
}

```
and the result is 
```
[vagrant@testbox directio-test]$ go run main.go
block is 3000
```
which I expect to see is 4096

**Comment by yumsai** [comment]
In fact, this problem can be completely transformed into finding the result of address of the first element & alignment size.
So now my confusion is why the op of "&" can drive of the offset of alignment.

**Comment by ncw** [comment]
I see your confusion now.  `directio.AlignedBlock` will return only the size that you asked for but it is guaranteed to be aligned to a page boundary.

```go
package main

import (
	"fmt"

	"github.com/ncw/directio"
)

func main() {
	block := directio.AlignedBlock(3000)
	fmt.Printf("block is %d\n", len(block))
	fmt.Printf("block is at %p", &block[0])
}
```

Prints

```
block is 3000
block is at 0xc00007e000
``

so the block is clearly aligned.

I'll close this now as I think the question is answered.
https://go.dev/play/p/mcHTD5COgBi

**Comment by xujihui1985** [comment]
thanks for the clarify

**Comment by ncw** [comment]
No probs!

I'll close this now.

**Comment by morrychan** [comment]
in this test code, if its ok when the block which size is 3000 is write to a file in driect IO?
