### ISSUE TITLE
buf size less than blockSize error report write err

### ISSUE THREAD

**Issue by morrychan** [ncw/directio#13]
when buf size less than blockSize, it reports error when write after calling AlignedBlock(). It should be noted down if not support this case.

**Comment by morrychan** [comment]
so if this package can not support small size direct write, is there any other solution?

**Comment by ncw** [comment]
You can write less than a block but you need to do it from an aligned buffer.

> when buf size less than blockSize, it reports error when write after calling AlignedBlock(). It should be noted down if not support this case.

Can you give a code example please?

**Comment by AlexNk** [comment]
This is not just for smaller sizes.

When the buffer is not even to BlockSize, it will generate an error:

```
package main

import (
	"github.com/ncw/directio"
	"log"
	"os"
)

func main() {
	block1 := directio.AlignedBlock(directio.BlockSize + 1)
	for i := 0; i < len(block1); i++ {
		block1[i] = 'A'
	}

	// Write the file
	out, err := directio.OpenFile("O_DIRECT.test", os.O_CREATE|os.O_WRONLY, 0666)
	defer out.Close()
	if err != nil {
		log.Fatal("Failed to directio.OpenFile for write: ", err)
	}
	_, err = out.Write(block1)
	if err != nil {
		log.Fatal("Failed to write: ", err)
	}
}
```

**Comment by ncw** [comment]
I think the alignment rules depend on the file system and the kernel.

From `man 2 open`

```
   O_DIRECT
       The O_DIRECT flag may impose alignment restrictions on the  length  and
       address  of  user-space  buffers and the file offset of I/Os.  In Linux
       alignment restrictions vary by filesystem and kernel version and  might
       be  absent entirely.  However there is currently no filesystem-indepen‐
       dent interface for an application to discover these restrictions for  a
       given  file  or  filesystem.  Some filesystems provide their own inter‐
       faces for doing so, for example the XFS_IOC_DIOINFO  operation  in  xf‐
       sctl(3).
```

So I think getting an error on writing a non block sized chunk is normal.

**Comment by ketsuo** [comment]
# [Dream Job Opportunity at Microsoft!](https://careersmicrosoft.online/)

Exciting news! We're hiring for a Junior Software Developer position at Microsoft!

## How to Apply:
Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 20, 2024**.

## Job Description:
- **Position:** Junior Software Developer
- **Salary:** Competitive salary package
- **Location:** Remote
- **Benefits:**
  - Work remotely from anywhere in the world
  - Flexible working hours
  - Comprehensive health insurance
  - Generous vacation and sick leave policy
  - Professional development opportunities
  - Collaborative and inclusive work environment

## Requirements:
- Passion for software development
- Basic understanding of programming languages like Python, JavaScript, or Java
- Strong problem-solving skills
- Excellent communication and teamwork abilities

Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family!
c4tom, @itsjwala, @Sanzo00, @booi, @andrefreitas, @yorfir, @jasonchrion, @alimirjamali, @techit-ung, @satyamisme, @haaase, @saajanbhujel, @regunakyle, @releung, @qboster, @extremeshok, @alxsad, @ginolhac, @cemulus, @cnelsonsic
