### ISSUE TITLE
windows dda to physical drive

### ISSUE THREAD

**Issue by iu0v1** [ncw/directio#5]
Hello.
I have tried to access to a physical drive (flash drive on windows machine) by using this code:
```drive, err := directio.OpenFile(`\\.\PhysicalDrive9`, os.O_RDWR, 0666)```
But without root I can't get access to the device (`open \\.\PhysicalDrive9: Access is denied`).
Tried to play with different os.FileMode's, but the result remained the same. Please can you tell me if i fail with mode's/os.FileMode's, or direct access to the device can be got only with the admin rights only?
I would be very grateful for any help.

**Comment by ncw** [comment]
I'm pretty sure you'll need admin rights.  Direct access to the drive gives you the ability to forge access permissions on the file system, so I doubt mere users will be allowed that.

**Comment by iu0v1** [comment]
Sounds reasonably. Somehow I haven't thought of rewriting of permissions for FS by mere user. My mistake. Thanks a lot for the answer.
