### ISSUE TITLE
TestDirectIO fail on Fedora 26, Go version 1.7

### ISSUE THREAD

**Issue by smithjessk** [ncw/directio#7]
Reference Commit: 17018d97cb6f2cd62f84c69903d327e596b7a93e

`TestDirectIO` fails on my Linux system because of the mode `syscall.O_DIRECT`, which is set by `directio.OpenFile`. 

As proof, I noted that changing [line 29](https://github.com/ncw/directio/blob/17018d97cb6f2cd62f84c69903d327e596b7a93e/direct_io_test.go#L29) to use `os.OpenFile(path, os.O_CREATE|os.O_WRONLY, 0666)` eliminates the error. The only difference between these two calls is the use of `syscall.O_DIRECT`.

Has this mode been deprecated? Is this project still active? Thanks!

## System information ##

- `go version` = `go1.7 linux/amd64`
- `uname -a` = `Linux localhost.localdomain 4.13.16-202.fc26.x86_64 #1 SMP Thu Nov 30 15:39:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

## Test Output ##

```
[jess@localhost directio]$ go test
--- FAIL: TestDirectIo (0.00s)
	direct_io_test.go:32: Failed to directio.OpenFile for read open /tmp/direct_io_test087816965: invalid argument
FAIL
exit status 1
FAIL	directio	0.001s

```

**Comment by ncw** [comment]
This error

> Failed to directio.OpenFile for read open /tmp/direct_io_test087816965: invalid argument
FAIL

Likely means that the underlying FS doesn't support direct IO

from `man 2 open`

       EINVAL The filesystem does not support the O_DIRECT  flag.   See  NOTES
              for more information.

On your machine, what filing system is `/tmp` on?

What happens if you `export TMPDIR=$HOME` before running the tests - does that fix it?

**Comment by smithjessk** [comment]
`export TMPDIR=$HOME` fixes the issue. Thanks!
